# docker-composeのバージョン
version: "3"

# コンテナ定義
services:

   #webサーバー
#  nginx:
#    # コンテナ名
#    container_name: "nginx-test"
#    build:
#      dockerfile: "./nginx/Dockerfile"
#    ports:
#      - "80:80"

  # webサーバー
  web:
    # コンテナ名
    container_name: "web-api"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./web/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "8088:80"
    # src配下のファイルをコンテナ内の~/var/www/html配下に配置
    volumes:
      - "../php-api2:/var/www/html"
  #      - "./src:/var/www/html"

  # PHPサーバー
  php:
    # コンテナ名
    container_name: "php-api"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./php/Dockerfile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
    volumes:
      - "../php-api2:/var/www/html"
  #      - "./src:/var/www/html"

  #   DBサーバー
  db:
    # コンテナ名
    container_name: "db"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./db/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=test-db"
      - "MYSQL_USER=dev"
      - "MYSQL_PASSWORD=dev"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./db/data:/var/lib/mysql"